### ISSUE TITLE
[flutter_google_street_view] There is no callback to know if the street view is not available for a location.

### ISSUE THREAD

**Issue by skyloovportal** [zyzdev/flutter_street_view#2] opened 2021-09-30 06:46 UTC
Hey, I really appreciate your efforts but i would like to request for an update i.e If there is no street view available for a specific location please provide a callback in platform view in order to show a valid response to the user.

Thanks

**Comment by zyzdev** [comment] 2021-10-03 03:20
Hi, @skyloovportal 
Callback onPanoramaChangeListener can solve it. 
onPanoramaChangeListener callback function is 
`void Function(StreetViewPanoramaLocation? location, Exception? e){}`
and the `Exception? e` will not be null while the street view invalid.
Try the code shown below.
``` dart
const LatLng INVALID = LatLng(-45.125783, 151.276417);

FlutterGoogleStreetView(
  initPos: INVALID,
  onPanoramaChangeListener: (location, e) {
    print("location:$location, e:$e");
  },
);
```

//log
location:null, e:Exception: Oops..., no valid panorama found with position:-45.125783, 151.27641700000004, try to change `position`, `radius` or `source`.

**Comment by zyzdev** [comment] 2021-10-05 11:05
Close this issue here.
The callback `onPanoramaChangeListener` will receive exception while the street view invalid.
See demo `Street View Panorama events(demo/street_view_panorama_events.dart)` in `example` for usage.

**Closed by zyzdev** 2021-10-05 11:05 UTC

**Comment by yogi1610** [comment] 2024-09-28 07:59
@zyzdev 
Is there any solution for this package flutter_google_street_view: ^3.1.4?
Because app keeps continue crashing by giving following error
com.google.maps.api.android.lib6.common.apiexception.f: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:318)
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:3)
E/AndroidRuntime(29446): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(29446): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29446): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(29446): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(29446): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(29446): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29446): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(29446): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(29446): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime(29446): 	at zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange(Unknown Source:2)
E/AndroidRuntime(29446): 	at com.google.android.gms.maps.zzaj.zzb(com.google.android.gms:play-services-maps@@18.2.0:1)
E/AndroidRuntime(29446): 	at com.google.android.gms.maps.internal.zzbm.zza(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime(29446): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime(29446): 	at android.os.Binder.transact(Binder.java:1164)
E/AndroidRuntime(29446): 	at m.axi.c(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:8)
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:311)
